### ISSUE TITLE
idでのリンクで見たい箇所がヘッダーで被さってしまう

### ISSUE THREAD

**Issue by sapphi-red** [traPtitech/Ghost-Theme-2020#51]
`position: sticky`のせい

マイナスの`margin-top`とかでできるっぽい
できなかったらjsでなんとかする

**Comment by sapphi-red** [comment]
```css
html {
  scroll-padding-top: 3.5rem;
}
```
で直るっぽいのでpc表示のときだけつけるとよさそう
